/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_banco;

import business.ClientesBusiness;
import business.TelefonoBusiness;
import data.ClientesDAO;
import data.DireccionesDAO;
import domain.Cliente;
import domain.Cliente_Juridico;
import domain.Direcciones;
import domain.Telefonos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ClienteJuridico extends javax.swing.JFrame {
    private ArrayList <Direcciones>  lista;
    private String codDirrecion;

    /**
     * Creates new form CuentaCorriente
     */
    public ClienteJuridico() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            cargarComboboxCanton();
            cargarComboboxDistrito();
            codigo();
        } catch (Exception ex) {
            Logger.getLogger(ClienteJuridico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public void cargarComboboxCanton() throws SQLException, Exception{
        lista=new ArrayList();
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        
        DireccionesDAO dir= new DireccionesDAO();
        String provincia= (String) jComboBoxProvincias.getSelectedItem();
        lista=dir.obtenerCanton(provincia);
        String canton;
        for(Direcciones d:lista){
            canton=d.getCANTON();
            modelo.addElement(canton);
            
        }
        jComboBoxCanton.setModel(modelo);
        
    }
    
    public void cargarComboboxDistrito() throws SQLException, Exception{
        lista=new ArrayList();
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        
        DireccionesDAO dir= new DireccionesDAO();
        String provincia= (String) jComboBoxProvincias.getSelectedItem();
        String canton= (String) jComboBoxCanton.getSelectedItem();
        lista=dir.obtenerDistrito(provincia, canton);
        String distrito;
        for(Direcciones d:lista){
            distrito=d.getDISTRITO();
            modelo.addElement(distrito);
            
        }
        jComboBoxDistrito.setModel(modelo);
        
    }
    
    
    public void codigo() throws SQLException{
        DireccionesDAO dir= new DireccionesDAO();
        Direcciones direccion = new Direcciones();
        direccion.setPROVINCIA((String) jComboBoxProvincias.getSelectedItem());
        direccion.setCANTON((String) jComboBoxCanton.getSelectedItem());
        direccion.setDISTRITO((String) jComboBoxDistrito.getSelectedItem());
        dir.obtenerDireccion(direccion);
        codDirrecion=direccion.getCod_direccion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice5 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel4 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedulaJuridica = new javax.swing.JTextField();
        cel1 = new javax.swing.JTextField();
        tel1 = new javax.swing.JTextField();
        tel2 = new javax.swing.JTextField();
        buttonAeroRight1 = new org.edisoncor.gui.button.ButtonAeroRight();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tel3 = new javax.swing.JTextField();
        cel2 = new javax.swing.JTextField();
        jComboBoxProvincias = new javax.swing.JComboBox();
        jComboBoxDistrito = new javax.swing.JComboBox();
        jComboBoxCanton = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCurves1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cedula Juridica:");
        panelCurves1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 20));
        panelCurves1.add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Empresa:");
        panelCurves1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 20));
        panelCurves1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelCurves1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelCurves1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente Juridico");
        panelCurves1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        panelCurves1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));
        panelCurves1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 100, 20));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        panelCurves1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 20));

        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        panelCurves1.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Segundo Apellido:");
        panelCurves1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Primer Apellido:");
        panelCurves1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        txtCedulaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaJuridicaActionPerformed(evt);
            }
        });
        panelCurves1.add(txtCedulaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 80, -1));
        panelCurves1.add(cel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 60, -1));
        panelCurves1.add(tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 60, -1));
        panelCurves1.add(tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 60, -1));

        buttonAeroRight1.setBackground(new java.awt.Color(102, 102, 102));
        buttonAeroRight1.setText("Regresar");
        buttonAeroRight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAeroRight1ActionPerformed(evt);
            }
        });
        panelCurves1.add(buttonAeroRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id Cliente:");
        panelCurves1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Direcciones:");
        panelCurves1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));
        panelCurves1.add(tel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, -1));
        panelCurves1.add(cel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 60, -1));

        jComboBoxProvincias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San Jose", "Cartago", "Alajuela", "Guanacaste", "Limon", "Heredia", "Puntarenas" }));
        jComboBoxProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProvinciasActionPerformed(evt);
            }
        });
        panelCurves1.add(jComboBoxProvincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, -1));

        jComboBoxDistrito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDistritoActionPerformed(evt);
            }
        });
        panelCurves1.add(jComboBoxDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, -1));

        jComboBoxCanton.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCantonActionPerformed(evt);
            }
        });
        panelCurves1.add(jComboBoxCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefonos:");
        panelCurves1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        panelNice5.add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        getContentPane().add(panelNice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void buttonAeroRight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAeroRight1ActionPerformed
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAeroRight1ActionPerformed

    private void jComboBoxProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProvinciasActionPerformed
        try {
            cargarComboboxCanton();
            codigo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxProvinciasActionPerformed

    private void jComboBoxCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCantonActionPerformed
        try {
            cargarComboboxDistrito();
            codigo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxCantonActionPerformed

    private void jComboBoxDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDistritoActionPerformed
        try {
           codigo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxDistritoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            ClientesDAO clientesDAO = new ClientesDAO();
            
            Cliente cliente = new Cliente();
            cliente.setTipo_cliente(2);
            clientesDAO.agregarCliente(cliente);
            
            Cliente_Juridico clienteJuridico = new Cliente_Juridico();
            clienteJuridico.setId_cliente(clientesDAO.ultimoID());
            clienteJuridico.setCed_juridica(Integer.parseInt(txtCedulaJuridica.getText()));
            clienteJuridico.setNombre_Representante(txtNombre.getText());
            clienteJuridico.setApellido1(txtApellido1.getText());
            clienteJuridico.setApellido2(txtApellido2.getText());
            clienteJuridico.setNombre_Empresa(txtEmpresa.getText());
            clienteJuridico.setCodDireccion(codDirrecion);
            
            TelefonoBusiness telefonoBusiness = new TelefonoBusiness();
            
            Telefonos telefonos= new Telefonos();
            telefonos.setTelefono1(tel1.getText());
            telefonos.setTelefono2(tel2.getText());
            telefonos.setTelefono3(tel3.getText());
            telefonos.setCelular1(cel1.getText());
            telefonos.setCelular2(cel2.getText());
            telefonoBusiness.agregarTelefonos(telefonos);
            
            clienteJuridico.setCod_telefono(telefonos.getCod_telefono());
            
            clientesDAO.agregarCliente_juridico(clienteJuridico);
            
            JOptionPane.showMessageDialog(panelCurves1, "El cliente ha sido agregado correctemente ");
            
            
        } catch (Exception ex) {
             Logger.getLogger(ClienteJuridico.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtCedulaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaJuridicaActionPerformed
        ClientesDAO cli = new ClientesDAO();
        
        Cliente_Juridico cliente_Juridico = new Cliente_Juridico();
        cliente_Juridico.setId_cliente(Integer.parseInt(txtCedulaJuridica.getText()));
        
        
        try{
            cli.obtenerDatosClienteJuridico(cliente_Juridico);
            txtEmpresa.setText(cliente_Juridico.getNombre_Empresa().trim());
            txtNombre.setText(cliente_Juridico.getNombre_Representante().trim());
            txtApellido1.setText(cliente_Juridico.getApellido1().trim());
            txtApellido2.setText(cliente_Juridico.getApellido2().trim());
            
            //tel1.setText(cliente_Juridico.getCod_telefonos().trim());
            
            codDirrecion = cliente_Juridico.getCodDireccion();
            
        } catch (Exception ex) {
            Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCedulaJuridicaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ClientesBusiness clienteBusniess = new ClientesBusiness();
        
        Cliente_Juridico cliente_Juridico = new Cliente_Juridico();
        
        cliente_Juridico.setCed_juridica(Integer.parseInt(txtCedulaJuridica.getText()));
        cliente_Juridico.setNombre_Empresa(txtEmpresa.getText());
        cliente_Juridico.setNombre_Representante(txtNombre.getText());
        cliente_Juridico.setApellido1(txtApellido1.getText());
        cliente_Juridico.setApellido2(txtApellido2.getText());
        cliente_Juridico.setCodDireccion(codDirrecion);
        
        TelefonoBusiness telefonoBusiness = new TelefonoBusiness();
            
            Telefonos telefonos= new Telefonos();
            telefonos.setTelefono1(tel1.getText());
            telefonos.setTelefono2(tel2.getText());
            telefonos.setTelefono3(tel3.getText());
            telefonos.setCelular1(cel1.getText());
            telefonos.setCelular2(cel2.getText());
        try {
            telefonoBusiness.agregarTelefonos(telefonos);
            cliente_Juridico.setCod_telefono(telefonos.getCod_telefono());
            clienteBusniess.actualizarClienteJuridico(cliente_Juridico);
            JOptionPane.showMessageDialog(panelCurves1, "El cliente ha sido actualizado correctemente ");
        } catch (Exception ex) {
            Logger.getLogger(ClienteJuridico.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_btnActualizarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteJuridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteJuridico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight1;
    private javax.swing.JTextField cel1;
    private javax.swing.JTextField cel2;
    private javax.swing.JComboBox jComboBoxCanton;
    private javax.swing.JComboBox jComboBoxDistrito;
    private javax.swing.JComboBox jComboBoxProvincias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice5;
    private javax.swing.JTextField tel1;
    private javax.swing.JTextField tel2;
    private javax.swing.JTextField tel3;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCedulaJuridica;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
