/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_banco;

import business.ClientesBusiness;
import business.TelefonoBusiness;
import data.ClientesDAO;
import data.DireccionesDAO;
import data.TelefonoDAO;
import domain.Cliente;
import domain.Cliente_Fisico;
import domain.Direcciones;
import domain.Padron;
import domain.Telefonos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ClienteFisico extends javax.swing.JFrame {
    private ArrayList <Direcciones>  lista;
    private String codDirrecion;

    /**
     * Creates new form CuentaCorriente
     */
    public ClienteFisico() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            cargarComboboxCanton();
            cargarComboboxDistrito();
            codigo();
            txtNombre.setEditable(false);
            txtApellido1.setEditable(false);
            txtApellido2.setEditable(false);
            txtCorreo.setEditable(false);
            tel1.setEditable(false);
            tel2.setEditable(false);
            tel3.setEditable(false);
            cel1.setEditable(false);
            cel2.setEditable(false);
            jDateChooser1.setEnabled(false);
            
        } catch (Exception ex) {
            Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void cargarComboboxCanton() throws SQLException, Exception{
        lista=new ArrayList();
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        
        DireccionesDAO dir= new DireccionesDAO();
        String provincia= (String) jComboBoxProvincias.getSelectedItem();
        lista=dir.obtenerCanton(provincia);
        String canton;
        for(Direcciones d:lista){
            canton=d.getCANTON();
            modelo.addElement(canton);
            
        }
        jComboBoxCanton.setModel(modelo);
        
    }
    
    public void cargarComboboxDistrito() throws SQLException, Exception{
        lista=new ArrayList();
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        
        DireccionesDAO dir= new DireccionesDAO();
        String provincia= (String) jComboBoxProvincias.getSelectedItem();
        String canton= (String) jComboBoxCanton.getSelectedItem();
        lista=dir.obtenerDistrito(provincia, canton);
        String distrito;
        for(Direcciones d:lista){
            distrito=d.getDISTRITO();
            modelo.addElement(distrito);
            
        }
        jComboBoxDistrito.setModel(modelo);
        
    }
    
    
    public void codigo() throws SQLException{
        DireccionesDAO dir = new DireccionesDAO();
        Direcciones direccion = new Direcciones();
        direccion.setPROVINCIA((String) jComboBoxProvincias.getSelectedItem());
        direccion.setCANTON((String) jComboBoxCanton.getSelectedItem());
        direccion.setDISTRITO((String) jComboBoxDistrito.getSelectedItem());
        dir.obtenerDireccion(direccion);
        codDirrecion=direccion.getCod_direccion();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice5 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        tel3 = new javax.swing.JTextField();
        cel2 = new javax.swing.JTextField();
        tel2 = new javax.swing.JTextField();
        buttonAeroRight1 = new org.edisoncor.gui.button.ButtonAeroRight();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        tel1 = new javax.swing.JTextField();
        cel1 = new javax.swing.JTextField();
        jComboBoxDistrito = new javax.swing.JComboBox();
        jComboBoxProvincias = new javax.swing.JComboBox();
        jComboBoxCanton = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCurves1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cedula:");
        panelCurves1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 20));
        panelCurves1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, -1));
        panelCurves1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelCurves1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelCurves1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Cliente:");
        panelCurves1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        panelCurves1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion:");
        panelCurves1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 20));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        panelCurves1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Segundo Apellido:");
        panelCurves1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Primer Apellido:");
        panelCurves1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Celulares:");
        panelCurves1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 20));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        panelCurves1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 90, -1));
        panelCurves1.add(tel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 60, -1));
        panelCurves1.add(cel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 60, -1));
        panelCurves1.add(tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 60, -1));

        buttonAeroRight1.setBackground(new java.awt.Color(102, 102, 102));
        buttonAeroRight1.setText("Regresar");
        buttonAeroRight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAeroRight1ActionPerformed(evt);
            }
        });
        panelCurves1.add(buttonAeroRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cliente Fisico");
        panelCurves1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 20));
        panelCurves1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de Nacimiento:");
        panelCurves1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, 20));
        panelCurves1.add(tel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 60, -1));
        panelCurves1.add(cel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 60, -1));

        jComboBoxDistrito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDistritoActionPerformed(evt);
            }
        });
        panelCurves1.add(jComboBoxDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 110, -1));

        jComboBoxProvincias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxProvincias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San Jose", "Cartago", "Alajuela", "Guanacaste", "Limon", "Heredia", "Puntarenas" }));
        jComboBoxProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProvinciasActionPerformed(evt);
            }
        });
        panelCurves1.add(jComboBoxProvincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, -1));

        jComboBoxCanton.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCantonActionPerformed(evt);
            }
        });
        panelCurves1.add(jComboBoxCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo:");
        panelCurves1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Telefonos:");
        panelCurves1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 20));
        panelCurves1.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));
        panelCurves1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, -1));

        panelNice5.add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        getContentPane().add(panelNice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAeroRight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAeroRight1ActionPerformed
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAeroRight1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        try {       
            
            ClientesBusiness clienteBusniess = new ClientesBusiness();
            
            Cliente cliente = new Cliente();
            cliente.setTipo_cliente(1);
            try {
                clienteBusniess.agregarCliente(cliente);
            } catch (Exception ex) {
                Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Cliente_Fisico clienteFisico = new Cliente_Fisico();
            
            clienteFisico.setCedula(Integer.parseInt(txtCedula.getText()));
            clienteFisico.setNombre(txtNombre.getText());
            clienteFisico.setApellido1(txtApellido1.getText());
            clienteFisico.setApellido2(txtApellido2.getText());
            clienteFisico.setCodDireccion(codDirrecion);
            clienteFisico.setCorreo(txtCorreo.getText());
            
            int dia=jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mes=jDateChooser1.getCalendar().get(Calendar.MONTH);
            int año=jDateChooser1.getCalendar().get(Calendar.YEAR);
            String fecha=año+"/"+mes+"/"+dia;
            clienteFisico.setFec_nacimiento(fecha);
            
            TelefonoBusiness telefonoBusiness = new TelefonoBusiness();
            
            Telefonos telefonos= new Telefonos();
            telefonos.setTelefono1(tel1.getText());
            telefonos.setTelefono2(tel2.getText());
            telefonos.setTelefono3(tel3.getText());
            telefonos.setCelular1(cel1.getText());
            telefonos.setCelular2(cel2.getText());
            telefonoBusiness.agregarTelefonos(telefonos);
            
            clienteFisico.setCod_telefonos(telefonos.getCod_telefono());
            
        try {
                
            clienteBusniess.agregarClienteFisico(clienteFisico);
            
            JOptionPane.showMessageDialog(panelCurves1, "El cliente ha sido agregado correctemente ");
        }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }catch(SQLException ex){
            Logger.getLogger(ClienteFisico.class.getName()).log( Level.SEVERE, null, ex);
        }catch(Exception ex){
            Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jComboBoxProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProvinciasActionPerformed
        try {
            cargarComboboxCanton();
            codigo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxProvinciasActionPerformed

    private void jComboBoxCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCantonActionPerformed
        try {
            cargarComboboxDistrito();
            codigo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxCantonActionPerformed

    private void jComboBoxDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDistritoActionPerformed
        try {
           codigo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxDistritoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
         //txtIdCliente.setEditable(false);
        btnActualizar.setEnabled(false);
        
            txtNombre.setEditable(true);
            txtApellido1.setEditable(true);
            txtApellido2.setEditable(true);
            txtCorreo.setEditable(true);
            tel1.setEditable(true);
            tel2.setEditable(true);
            tel3.setEditable(true);
            cel1.setEditable(true);
            cel2.setEditable(true);
            jDateChooser1.setEnabled(true);
        
        ClientesDAO cli = new ClientesDAO();
        
        Padron padron = new Padron();
        padron.setCEDULA(txtCedula.getText());
        
        try {
            cli.obtenerDatos(padron);
            txtNombre.setText(padron.getNOMBRE().trim());
            txtApellido1.setText(padron.getAPELLIDO_1().trim());
            txtApellido2.setText(padron.getAPELLIDO_2().trim());
            codDirrecion=padron.getCODELEC().trim();
        } catch (Exception ex) {
            Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {       
            
            ClientesBusiness clienteBusniess = new ClientesBusiness();
            
            Cliente_Fisico clienteFisico = new Cliente_Fisico();
            
            clienteFisico.setCedula(Integer.parseInt(txtCedula.getText()));
            clienteFisico.setNombre(txtNombre.getText());
            clienteFisico.setApellido1(txtApellido1.getText());
            clienteFisico.setApellido2(txtApellido2.getText());
            clienteFisico.setCodDireccion(codDirrecion);
            clienteFisico.setCorreo(txtCorreo.getText());
            
            int dia=jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mes=jDateChooser1.getCalendar().get(Calendar.MONTH);
            int año=jDateChooser1.getCalendar().get(Calendar.YEAR);
            String fecha=año+"/"+mes+"/"+dia;
            clienteFisico.setFec_nacimiento(fecha);
            
            
            TelefonoBusiness telefonoBusiness = new TelefonoBusiness();
            
            Telefonos telefonos= new Telefonos();
            telefonos.setTelefono1(tel1.getText());
            telefonos.setTelefono2(tel2.getText());
            telefonos.setTelefono3(tel3.getText());
            telefonos.setCelular1(cel1.getText());
            telefonos.setCelular2(cel2.getText());
            telefonoBusiness.agregarTelefonos(telefonos);
            
            clienteFisico.setCod_telefonos(telefonos.getCod_telefono());
            
        try {
                
            clienteBusniess.actualizarClienteFisico(clienteFisico);
            
            JOptionPane.showMessageDialog(panelCurves1, "El cliente ha sido actualizado correctemente ");
            
            
        }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }catch(SQLException ex){
            Logger.getLogger(ClienteFisico.class.getName()).log( Level.SEVERE, null, ex);
    }   catch (Exception ex) {
            Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        
        btnAgregar.setEnabled(false);
        
            txtNombre.setEditable(true);
            txtApellido1.setEditable(true);
            txtApellido2.setEditable(true);
            txtCorreo.setEditable(true);
            tel1.setEditable(true);
            tel2.setEditable(true);
            tel3.setEditable(true);
            cel1.setEditable(true);
            cel2.setEditable(true);
            jDateChooser1.setEnabled(true);
        
        ClientesDAO cli = new ClientesDAO();
        
        Cliente_Fisico cliente_Fisico = new Cliente_Fisico();
        cliente_Fisico.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        
        
        try{
            cli.obtenerDatosIdCliente(cliente_Fisico);
            txtCedula.setText(String.valueOf(cliente_Fisico.getCedula()));
            txtNombre.setText(cliente_Fisico.getNombre().trim());
            txtApellido1.setText(cliente_Fisico.getApellido1().trim());
            txtApellido2.setText(cliente_Fisico.getApellido2().trim());
            txtCorreo.setText(cliente_Fisico.getCorreo().trim());
            //tel1.setText(cliente_Fisico.getCod_telefonos().trim());
            
            codDirrecion = cliente_Fisico.getCodDireccion().trim();
            
        } catch (Exception ex) {
            Logger.getLogger(ClienteFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIdClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteFisico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight1;
    private javax.swing.JTextField cel1;
    private javax.swing.JTextField cel2;
    private javax.swing.JComboBox jComboBoxCanton;
    private javax.swing.JComboBox jComboBoxDistrito;
    private javax.swing.JComboBox jComboBoxProvincias;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice5;
    private javax.swing.JTextField tel1;
    private javax.swing.JTextField tel2;
    private javax.swing.JTextField tel3;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
