/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_banco;

import java.awt.Image;
import java.awt.List;
import java.awt.Panel;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import org.edisoncor.gui.panel.PanelAvatarChooser;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAvatarChooser1 = new org.edisoncor.gui.panel.PanelAvatarChooser();
        panelAvatarChooser3 = new org.edisoncor.gui.panel.PanelAvatarChooser();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        panelReflect1 = new org.edisoncor.gui.panel.PanelReflect();
        btnClientes = new org.edisoncor.gui.button.ButtonIcon();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        btnCreditos = new org.edisoncor.gui.button.ButtonIcon();
        btnCuentas = new org.edisoncor.gui.button.ButtonIcon();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        buttonTask1 = new org.edisoncor.gui.button.ButtonTask();
        jComboBoxCreditos = new javax.swing.JComboBox();
        jComboBoxCuentas = new javax.swing.JComboBox();
        jComboBoxConsultas = new javax.swing.JComboBox();
        jComboBoxClientes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReflect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.jpg"))); // NOI18N
        btnClientes.setText("buttonIcon1");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelReflect1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 100, 100));

        labelMetric2.setText("Creditos");
        labelMetric2.setFont(new java.awt.Font("BankGothic Md BT", 1, 18)); // NOI18N
        panelReflect1.add(labelMetric2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 100, -1));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuenta de credito.jpg"))); // NOI18N
        btnCreditos.setText("buttonIcon1");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        panelReflect1.add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 100, 100));

        btnCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dolar.png"))); // NOI18N
        btnCuentas.setText("buttonIcon1");
        btnCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasActionPerformed(evt);
            }
        });
        panelReflect1.add(btnCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 110, 100));

        labelMetric3.setText("Cuentas");
        labelMetric3.setFont(new java.awt.Font("BankGothic Md BT", 1, 18)); // NOI18N
        panelReflect1.add(labelMetric3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, -1));

        labelMetric4.setText("Clientes");
        labelMetric4.setFont(new java.awt.Font("BankGothic Md BT", 1, 18)); // NOI18N
        panelReflect1.add(labelMetric4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 100, -1));

        buttonTask1.setForeground(new java.awt.Color(255, 255, 255));
        buttonTask1.setText("Consultas");
        buttonTask1.setDescription("    ");
        buttonTask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTask1ActionPerformed(evt);
            }
        });
        panelReflect1.add(buttonTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jComboBoxCreditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Credito Personal", "Credito Prendario", "Credito Hipotecario" }));
        panelReflect1.add(jComboBoxCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 140, -1));

        jComboBoxCuentas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuenta Corriente", "Cuenta de Ahorro" }));
        panelReflect1.add(jComboBoxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 150, -1));

        jComboBoxConsultas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuenta", "Cliente", "Credito" }));
        panelReflect1.add(jComboBoxConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, -1));

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente Fisico", "Cliente Juridico" }));
        panelReflect1.add(jComboBoxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 140, -1));

        panelNice2.add(panelReflect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 600));

        getContentPane().add(panelNice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 940, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTask1ActionPerformed
        // TODO add your handling code here:
        int consultaElegida = jComboBoxConsultas.getSelectedIndex();
        
        if(consultaElegida == 0){
            CuentaConsulta cuentaConsulta = new CuentaConsulta();
            cuentaConsulta.setVisible(true);
            this.dispose();
        }else if(consultaElegida == 1){
            ClienteConsulta clienteConsulta = new ClienteConsulta();
            clienteConsulta.setVisible(true);
            this.dispose();
        }else if(consultaElegida == 2){
            CreditoConsulta creditoConsulta = new CreditoConsulta();
            creditoConsulta.setVisible(true);
            this.dispose();
        };
    }//GEN-LAST:event_buttonTask1ActionPerformed

    private void btnCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasActionPerformed
        // TODO add your handling code here:
        int cuentaElegida = jComboBoxCuentas.getSelectedIndex();
        
        if(cuentaElegida == 0){
            CuentaCorriente cuentaCorriente = new CuentaCorriente();
            cuentaCorriente.setVisible(true);
            this.dispose();
        }else if(cuentaElegida == 1){
            CuentaAhorro cuentaAhorro = new CuentaAhorro();
            cuentaAhorro.setVisible(true);
            this.dispose();
        };
    }//GEN-LAST:event_btnCuentasActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        int creditoElegido = jComboBoxCreditos.getSelectedIndex();
        
        if(creditoElegido == 0){
            CreditoPersonal creditoPersonal = new CreditoPersonal();
            creditoPersonal.setVisible(true);
            this.dispose();
        }else if(creditoElegido == 1){
            CreditoPrendario creditoPrendario = new CreditoPrendario();
            creditoPrendario.setVisible(true);
            this.dispose();
        }else if(creditoElegido == 2){
            CreditoHipotecario creditoHipotecario = new CreditoHipotecario();
            creditoHipotecario.setVisible(true);
            this.dispose();
        };
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        int clienteElegido = jComboBoxClientes.getSelectedIndex();
        
        if(clienteElegido == 0){
            ClienteFisico clienteFisico = new ClienteFisico();
            clienteFisico.setVisible(true);
            this.dispose();
        }else if(clienteElegido == 1){
            ClienteJuridico clienteJuridico = new ClienteJuridico();
            clienteJuridico.setVisible(true);
            this.dispose();
        };
    }//GEN-LAST:event_btnClientesActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon btnClientes;
    private org.edisoncor.gui.button.ButtonIcon btnCreditos;
    private org.edisoncor.gui.button.ButtonIcon btnCuentas;
    private org.edisoncor.gui.button.ButtonTask buttonTask1;
    private javax.swing.JComboBox jComboBoxClientes;
    private javax.swing.JComboBox jComboBoxConsultas;
    private javax.swing.JComboBox jComboBoxCreditos;
    private javax.swing.JComboBox jComboBoxCuentas;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.panel.PanelAvatarChooser panelAvatarChooser1;
    private org.edisoncor.gui.panel.PanelAvatarChooser panelAvatarChooser3;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private org.edisoncor.gui.panel.PanelReflect panelReflect1;
    // End of variables declaration//GEN-END:variables
}
